In [2]:
import duckdb

In [3]:
duckdb.read_csv("../raw_data/google_ads/*.csv")

┌─────────────┬─────────────┬──────────────────────┬─────────────┬───────────┬─────────────┬────────┬──────────────┐
│    date     │ campaign_id │    campaign_name     │   channel   │ spend_usd │ impressions │ clicks │ soft_deleted │
│   varchar   │    int64    │       varchar        │   varchar   │  double   │    int64    │ int64  │   boolean    │
├─────────────┼─────────────┼──────────────────────┼─────────────┼───────────┼─────────────┼────────┼──────────────┤
│ 30-Mar-2025 │           1 │ Brand Awareness Q1   │ Search      │    281.27 │       31784 │    814 │ false        │
│ 2025-03-30  │           5 │ New User Acquisition │ Search      │     299.1 │       31775 │   1441 │ false        │
│ 2025-03-30  │          21 │ Dynamic Search Ads   │ Paid Search │    238.37 │       43935 │   2773 │ false        │
│ 03/31/2025  │           1 │ Brand Awareness Q1   │ SEARCH      │    317.87 │       39921 │   1402 │ false        │
│ 31-Mar-2025 │           5 │ New User Acquisition │ Paid Search │    509.65 │       74533 │   5072 │ false        │
│ 2025-03-31  │          21 │ Dynamic Search Ads   │ SEARCH      │    167.15 │       19176 │    298 │ false        │
│ 01-Apr-2025 │           1 │ Brand Awareness Q1   │ Paid Search │    287.15 │       30191 │    866 │ false        │
│ 01-Apr-2025 │           5 │ New User Acquisition │ search      │    335.86 │       37748 │   2822 │ false        │
│ 01-Apr-2025 │          21 │ Dynamic Search Ads   │ SEARCH      │    173.32 │       19434 │    481 │ false        │
│ 02-Apr-2025 │           1 │ Brand Awareness Q1   │ SEARCH      │    421.91 │       47163 │   1285 │ false        │
│      ·      │           · │         ·            │   ·         │       ·   │         ·   │     ·  │  ·           │
│      ·      │           · │         ·            │   ·         │       ·   │         ·   │     ·  │  ·           │
│      ·      │           · │         ·            │   ·         │       ·   │         ·   │     ·  │  ·           │
│ 28-Mar-2026 │          16 │ Competitor Conquest  │ paid_search │    179.54 │       26822 │    803 │ true         │
│ 2026-03-28  │          21 │ Dynamic Search Ads   │ SEARCH      │    380.23 │       62339 │   1371 │ false        │
│ 29-Mar-2026 │           4 │ Holiday Promo        │ SHOPPING    │    766.21 │       81389 │   4093 │ false        │
│ 03/29/2026  │           5 │ New User Acquisition │ search      │    392.76 │       78443 │   4958 │ false        │
│ 03/29/2026  │          16 │ Competitor Conquest  │ SEARCH      │    183.03 │       21261 │   1480 │ false        │
│ 2026-03-29  │          21 │ Dynamic Search Ads   │ Search      │     284.1 │       52017 │    977 │ false        │
│ 30-Mar-2026 │           4 │   Holiday Promo      │ SHOPPING    │    633.65 │       61974 │   3270 │ false        │
│ 03/30/2026  │           5 │ New User Acquisition │ Search      │    416.78 │       76542 │   2551 │ false        │
│ 2026-03-30  │          16 │ Competitor Conquest  │ search      │    128.37 │       20706 │    890 │ false        │
│ 03/30/2026  │          21 │ Dynamic Search Ads   │ SEARCH      │    363.91 │       40514 │   1427 │ false        │
├─────────────┴─────────────┴──────────────────────┴─────────────┴───────────┴─────────────┴────────┴──────────────┤
│ 2092 rows (20 shown)                                                                                   8 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [4]:
conn = duckdb.connect("marketing_data.duckdb")

conn.execute(""" CREATE SCHEMA IF NOT EXISTS raw""")

conn.execute("""
    CREATE TABLE IF NOT EXISTS raw.google_ads AS
    SELECT * FROM read_csv('../raw_data/google_ads/*.csv')
""")

In [5]:
conn.execute("show all tables").fetchdf()

,database,schema,name,column_names,column_types,temporary
0,marketing_data,raw,google_ads,"[date, campaign_id, campaign_name, channel, sp...","[VARCHAR, BIGINT, VARCHAR, VARCHAR, DOUBLE, BI...",False

In [6]:
conn.execute("select * from raw.google_ads limit 10").fetchdf()

,date,campaign_id,campaign_name,channel,spend_usd,impressions,clicks,soft_deleted
0,30-Mar-2025,1,Brand Awareness Q1,Search,281.27,31784,814,False
1,2025-03-30,5,New User Acquisition,Search,299.10,31775,1441,False
2,2025-03-30,21,Dynamic Search Ads,Paid Search,238.37,43935,2773,False
3,03/31/2025,1,Brand Awareness Q1,SEARCH,317.87,39921,1402,False
4,31-Mar-2025,5,New User Acquisition,Paid Search,509.65,74533,5072,False
5,2025-03-31,21,Dynamic Search Ads,SEARCH,167.15,19176,298,False
6,01-Apr-2025,1,Brand Awareness Q1,Paid Search,287.15,30191,866,False
7,01-Apr-2025,5,New User Acquisition,search,335.86,37748,2822,False
8,01-Apr-2025,21,Dynamic Search Ads,SEARCH,173.32,19434,481,False
9,02-Apr-2025,1,Brand Awareness Q1,SEARCH,421.91,47163,1285,False

In [7]:
conn.execute("select count(*) from raw.google_ads").fetchdf()

   count_star()
0          2092

In [8]:
conn.execute("select campaign_name, count(*) from raw.google_ads group by campaign_name").fetchdf()

                    campaign_name  count_star()
0            Brand Awareness Q1              18
1       Summer Sale - Retargeting           125
2       Summer Sale - Retargeting             8
3     Summer Sale - Retargeting               1
4            Dynamic Search Ads               2
5            Brand Awareness Q1               1
6            New User Acquisition            19
7                 YouTube Bumpers           190
8          App Install Campaign               1
9              Dynamic Search Ads           315
10             Brand Awareness Q1             2
11             Dynamic Search Ads            18
12            Competitor Conquest            10
13         Product Launch - Video             5
14          Competitor Conquest               1
15                 Back to School             8
16                  Holiday Promo            51
17              YouTube Bumpers              24
18          Competitor Conquest              32
19                YouTube Bumpers            11
20         App Install Campaign              23
21    Summer Sale - Retargeting              20
22                 Back to School            74
23                Holiday Promo               4
24           App Install Campaign            10
25         New User Acquisition              49
26               Back to School              11
27           New User Acquisition           309
28                Holiday Promo               1
29       Product Launch - Video               5
30              YouTube Bumpers               3
31                  Holiday Promo             6
32           Dynamic Search Ads              44
33         New User Acquisition               2
34           App Install Campaign           230
35             Brand Awareness Q1            71
36         Product Launch - Video            84
37            Competitor Conquest           304

In [9]:
conn.execute("select distinct channel from raw.google_ads").fetchdf()

             channel
0           SHOPPING
1            Display
2              video
3        Paid Search
4   product_shopping
5             search
6             SEARCH
7              Video
8            display
9            DISPLAY
10          Shopping
11            Search
12   display_network
13     youtube_video
14          shopping
15       paid_search
16             VIDEO

In [14]:
duckdb.read_json("../raw_data/segment/segment_tracks.jsonl")

┌──────────────────────────────────┬─────────┬────────────────┬─────────────────────────┬─────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
│            message_id            │  type   │     event      │        timestamp        │ user_id │ anonymous_id │                                                                                                                                   properties                                                                                                                                   │                                       context                                       │
│             varchar              │ varchar │    varchar     │         varchar         │ varchar │   varchar    │                  struct(campaign_id varchar, channel varchar, page_url varchar, product_id varchar, time_on_page bigint, product_name varchar, price_usd double, quantity bigint, query varchar, results_count bigint, cart_total double, item_count bigint)                   │      struct(library_name varchar, library_version varchar, user_agent varchar)      │
├──────────────────────────────────┼─────────┼────────────────┼─────────────────────────┼─────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ a55f626bb248f948693a07b3c16a4403 │ track   │ product_view   │ 2025-03-30 11:03:56 UTC │ u_04441 │ anon_292484  │ {'campaign_id': 8, 'channel': display, 'page_url': 'https://example.com/products', 'product_id': prod_7674, 'time_on_page': 85, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}       │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 6013c837d208975490c9d289fbfc44a7 │ track   │ add_to_cart    │ 2025-03-30 06:19:29 UTC │ u_00275 │ anon_378001  │ {'campaign_id': 6, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': prod_4406, 'time_on_page': NULL, 'product_name': Widget Pro, 'price_usd': 15.42, 'quantity': 2, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}   │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ b4841806a134ad30dba5160eb6fbf4fc │ track   │ search         │ 2025-03-30 17:53:01 UTC │ u_04133 │ anon_929916  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/about', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': best price, 'results_count': 36, 'cart_total': NULL, 'item_count': NULL}         │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 5b8d3bbc525b454e1f169344075c4923 │ track   │ page_view      │ 2025-03-30 04:56:51 UTC │ u_04773 │ anon_778044  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}           │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 37b3129cb8ff9bb06d34f5ee19213f9c │ track   │ search         │ 2025-03-30 08:12:02 UTC │ u_00528 │ anon_982347  │ {'campaign_id': 11, 'channel': search, 'page_url': 'https://example.com/about', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': widget, 'results_count': 9, 'cart_total': NULL, 'item_count': NULL}              │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 50dd26cf8aa2b3f8565d802724cc458e │ track   │ add_to_cart    │ 2025-03-30 05:52:35 UTC │ u_00385 │ anon_393948  │ {'campaign_id': 12, 'channel': display, 'page_url': 'https://example.com/pricing', 'product_id': prod_7403, 'time_on_page': NULL, 'product_name': Thing Plus, 'price_usd': 62.53, 'quantity': 3, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL} │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ b15781d6bd4e91583ba1a4b0b59e3946 │ track   │ add_to_cart    │ 2025-03-30 04:33:09 UTC │ u_01630 │ anon_345128  │ {'campaign_id': 6, 'channel': search, 'page_url': 'https://example.com/home', 'product_id': prod_3233, 'time_on_page': NULL, 'product_name': Widget Pro, 'price_usd': 48.98, 'quantity': 4, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}      │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ bd68c68ea4e9d96809f8def924904034 │ track   │ add_to_cart    │ 2025-03-30 00:14:01 UTC │ u_01766 │ anon_365959  │ {'campaign_id': 5, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': prod_8675, 'time_on_page': NULL, 'product_name': Doohickey, 'price_usd': 29.63, 'quantity': 1, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}    │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 9c7994a02c16a5d38171ea7de4549edc │ track   │ checkout_start │ 2025-03-30 00:28:54 UTC │ u_03738 │ anon_913596  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': 495.54, 'item_count': 6}            │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 778e92f6a4873c3499ebd712bf670592 │ track   │ page_view      │ 2025-03-30 05:17:41 UTC │ u_02041 │ anon_158772  │ {'campaign_id': 12, 'channel': display, 'page_url': 'https://example.com/home', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}             │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│                ·                 │   ·     │   ·            │            ·            │    ·    │      ·       │                                                                                                                                 ·                                                                                                                                              │                                          ·                                          │
│                ·                 │   ·     │   ·            │            ·            │    ·    │      ·       │                                                                                                                                 ·                                                                                                                                              │                                          ·                                          │
│                ·                 │   ·     │   ·            │            ·            │    ·    │      ·       │                                                                                                                                 ·                                                                                                                                              │                                          ·                                          │
│ e366956a5fb8e6b451f4c164b10deca2 │ track   │ search         │ 2025-04-13 21:15:08 UTC │ u_03495 │ anon_943901  │ {'campaign_id': 5, 'channel': search, 'page_url': 'https://example.com/about', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': best price, 'results_count': 33, 'cart_total': NULL, 'item_count': NULL}          │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ f0e0423f48051a57edb7bf6a96bd89d0 │ track   │ checkout_start │ 2025-04-13 19:24:26 UTC │ u_04990 │ anon_982322  │ {'campaign_id': 1, 'channel': search, 'page_url': 'https://example.com/home', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': 458.27, 'item_count': 7}                │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ f01651cbf133b04200fd07c77bc81cd9 │ track   │ checkout_start │ 2025-04-13 08:44:58 UTC │ N/A     │ anon_191073  │ {'campaign_id': 6, 'channel': search, 'page_url': 'https://example.com/home', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': 683.6, 'item_count': 7}                 │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 7d56055af2864eafa0a26907d1c2c433 │ track   │ page_view      │ 2025-04-13 12:38:33 UTC │ u_01044 │ anon_491697  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/home', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}              │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 75cbfb220a69c85909d35ed77d42a0c1 │ track   │ product_view   │ 2025-04-13 09:28:54 UTC │ u_03567 │ anon_905657  │ {'campaign_id': 11, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': prod_1497, 'time_on_page': 186, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}       │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 21e44783db3cd1cf642e1f310d1ccef3 │ track   │ search         │ 2025-04-13 06:06:14 UTC │ u_00840 │ anon_992705  │ {'campaign_id': 21, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': widget, 'results_count': 47, 'cart_total': NULL, 'item_count': NULL}           │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 745478978eea3104463fa598b69ed06e │ track   │ product_view   │ 2025-04-13 00:52:04 UTC │ u_00927 │ anon_113476  │ {'campaign_id': 5, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': prod_6034, 'time_on_page': 52, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}         │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 58e0f57f64c5c0cb3e9829db21de7f6c │ track   │ search         │ 2025-04-13 06:45:34 UTC │ u_04397 │ anon_166316  │ {'campaign_id': 21, 'channel': search, 'page_url': 'https://example.com/products', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': widget, 'results_count': 4, 'cart_total': NULL, 'item_count': NULL}           │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 7a20e9aef0c4ca9c3480bd5a3f1be1c7 │ track   │ search         │ 2025-04-13 14:39:00 UTC │ u_04673 │ anon_910085  │ {'campaign_id': 8, 'channel': display, 'page_url': 'https://example.com/products', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': review, 'results_count': 42, 'cart_total': NULL, 'item_count': NULL}          │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ f6cc6a3e15b0834f769ab7aad2a87ce9 │ track   │ search         │ 2025-04-13 18:45:02 UTC │ u_01908 │ anon_718869  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': discount, 'results_count': 45, 'cart_total': NULL, 'item_count': NULL}         │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
├──────────────────────────────────┴─────────┴────────────────┴─────────────────────────┴─────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                               8 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [30]:
conn.execute("""
    CREATE TABLE IF NOT EXISTS raw.segment_tracks AS
    SELECT 
        message_id,
        type,
        event,
        timestamp,
        user_id,
        anonymous_id,
        json(properties) as properties,
        json(context) as context,
        session_id
             
    FROM read_json('../raw_data/segment/segment_tracks.jsonl', sample_size=-1)

""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

**sample_size=-1 to force DuckDB to scan the entire file before inferring the schema**



[DuckDB Loading JSON Documentation](https://duckdb.org/docs/current/data/json/loading_json)

In [31]:
conn.execute("describe raw.segment_tracks").fetchdf()

    column_name column_type null   key default extra
0    message_id     VARCHAR  YES  None    None  None
1          type     VARCHAR  YES  None    None  None
2         event     VARCHAR  YES  None    None  None
3     timestamp     VARCHAR  YES  None    None  None
4       user_id     VARCHAR  YES  None    None  None
5  anonymous_id     VARCHAR  YES  None    None  None
6    properties        JSON  YES  None    None  None
7       context        JSON  YES  None    None  None
8    session_id     VARCHAR  YES  None    None  None

In [32]:
conn.execute("select * from raw.segment_tracks where message_id = 'a55f626bb248f948693a07b3c16a4403' ").fetch_df()

,message_id,type,event,timestamp,user_id,anonymous_id,properties,context,session_id
0,a55f626bb248f948693a07b3c16a4403,track,product_view,2025-03-30 11:03:56 UTC,u_04441,anon_292484,"{""campaign_id"":""8"",""channel"":""display"",""page_u...","{""library_name"":""analytics.js"",""library_versio...",None

In [33]:

conn.execute("select * from raw.segment_tracks where message_id = '56e5616e27be631a9130ae514fe7b818' ").fetch_df()

,message_id,type,event,timestamp,user_id,anonymous_id,properties,context,session_id
0,56e5616e27be631a9130ae514fe7b818,track,page_view,2025-06-28 02:52:16 UTC,u_00612,anon_836518,"{""campaign_id"":""16"",""channel"":""search"",""page_u...","{""library_name"":""analytics.js"",""library_versio...",sess_32372495