In [1]:
import duckdb

In [2]:
duckdb.read_csv("../raw_data/google_ads/*.csv")

┌─────────────┬─────────────┬──────────────────────┬─────────────┬───────────┬─────────────┬────────┬──────────────┐
│    date     │ campaign_id │    campaign_name     │   channel   │ spend_usd │ impressions │ clicks │ soft_deleted │
│   varchar   │    int64    │       varchar        │   varchar   │  double   │    int64    │ int64  │   boolean    │
├─────────────┼─────────────┼──────────────────────┼─────────────┼───────────┼─────────────┼────────┼──────────────┤
│ 04-Apr-2025 │           1 │ Brand Awareness Q1   │ Search      │    281.27 │       31784 │    814 │ false        │
│ 2025-04-04  │           5 │ New User Acquisition │ Search      │     299.1 │       31775 │   1441 │ false        │
│ 2025-04-04  │          21 │ Dynamic Search Ads   │ Paid Search │    238.37 │       43935 │   2773 │ false        │
│ 04/05/2025  │           1 │ Brand Awareness Q1   │ SEARCH      │    317.87 │       39921 │   1402 │ false        │
│ 05-Apr-2025 │           5 │ New User Acquisition │ Paid Search │    509.65 │       74533 │   5072 │ false        │
│ 2025-04-05  │          21 │ Dynamic Search Ads   │ SEARCH      │    167.15 │       19176 │    298 │ false        │
│ 06-Apr-2025 │           1 │ Brand Awareness Q1   │ Paid Search │    287.15 │       30191 │    866 │ false        │
│ 06-Apr-2025 │           5 │ New User Acquisition │ search      │    335.86 │       37748 │   2822 │ false        │
│ 06-Apr-2025 │          21 │ Dynamic Search Ads   │ SEARCH      │    173.32 │       19434 │    481 │ false        │
│ 07-Apr-2025 │           1 │ Brand Awareness Q1   │ SEARCH      │    421.91 │       47163 │   1285 │ false        │
│      ·      │           · │         ·            │   ·         │       ·   │         ·   │     ·  │  ·           │
│      ·      │           · │         ·            │   ·         │       ·   │         ·   │     ·  │  ·           │
│      ·      │           · │         ·            │   ·         │       ·   │         ·   │     ·  │  ·           │
│ 02-Apr-2026 │          16 │ Competitor Conquest  │ paid_search │    179.54 │       26822 │    803 │ true         │
│ 2026-04-02  │          21 │ Dynamic Search Ads   │ SEARCH      │    380.23 │       62339 │   1371 │ false        │
│ 03-Apr-2026 │           4 │ Holiday Promo        │ SHOPPING    │    766.21 │       81389 │   4093 │ false        │
│ 04/03/2026  │           5 │ New User Acquisition │ search      │    392.76 │       78443 │   4958 │ false        │
│ 04/03/2026  │          16 │ Competitor Conquest  │ SEARCH      │    183.03 │       21261 │   1480 │ false        │
│ 2026-04-03  │          21 │ Dynamic Search Ads   │ Search      │     284.1 │       52017 │    977 │ false        │
│ 04-Apr-2026 │           4 │   Holiday Promo      │ SHOPPING    │    633.65 │       61974 │   3270 │ false        │
│ 04/04/2026  │           5 │ New User Acquisition │ Search      │    416.78 │       76542 │   2551 │ false        │
│ 2026-04-04  │          16 │ Competitor Conquest  │ search      │    128.37 │       20706 │    890 │ false        │
│ 04/04/2026  │          21 │ Dynamic Search Ads   │ SEARCH      │    363.91 │       40514 │   1427 │ false        │
└─────────────┴─────────────┴──────────────────────┴─────────────┴───────────┴─────────────┴────────┴──────────────┘
  2088 rows (20 shown)                                                                                   8 columns

In [3]:
conn = duckdb.connect("marketing_data.duckdb")

conn.execute(""" CREATE SCHEMA IF NOT EXISTS raw""")

conn.execute("""
    CREATE TABLE IF NOT EXISTS raw.google_ads AS
    SELECT * FROM read_csv('../raw_data/google_ads/*.csv')
""")

In [4]:
conn.execute("show all tables").fetchdf()

,database,schema,name,column_names,column_types,temporary
0,marketing_data,raw,app_conversions,"[conversion_id, usr_id, cmpgn_id, conv_type_cd...","[INTEGER, INTEGER, INTEGER, INTEGER, DECIMAL(1...",False
1,marketing_data,raw,google_ads,"[date, campaign_id, campaign_name, channel, sp...","[VARCHAR, BIGINT, VARCHAR, VARCHAR, DOUBLE, BI...",False
2,marketing_data,raw,segment_tracks,"[message_id, type, event, timestamp, user_id, ...","[UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VAR...",False

In [5]:
conn.execute("select * from raw.google_ads limit 10").fetchdf()

,date,campaign_id,campaign_name,channel,spend_usd,impressions,clicks,soft_deleted
0,04-Apr-2025,1,Brand Awareness Q1,Search,281.27,31784,814,False
1,2025-04-04,5,New User Acquisition,Search,299.10,31775,1441,False
2,2025-04-04,21,Dynamic Search Ads,Paid Search,238.37,43935,2773,False
3,04/05/2025,1,Brand Awareness Q1,SEARCH,317.87,39921,1402,False
4,05-Apr-2025,5,New User Acquisition,Paid Search,509.65,74533,5072,False
5,2025-04-05,21,Dynamic Search Ads,SEARCH,167.15,19176,298,False
6,06-Apr-2025,1,Brand Awareness Q1,Paid Search,287.15,30191,866,False
7,06-Apr-2025,5,New User Acquisition,search,335.86,37748,2822,False
8,06-Apr-2025,21,Dynamic Search Ads,SEARCH,173.32,19434,481,False
9,07-Apr-2025,1,Brand Awareness Q1,SEARCH,421.91,47163,1285,False

In [6]:
conn.execute("select count(*) from raw.google_ads").fetchdf()

   count_star()
0          2088

In [7]:
conn.execute("select campaign_name, count(*) from raw.google_ads group by campaign_name").fetchdf()

                  campaign_name  count_star()
0          Brand Awareness Q1              17
1          Dynamic Search Ads              46
2        New User Acquisition               4
3          App Install Campaign           215
4                Back to School             6
5                 Holiday Promo            51
6          New User Acquisition           310
7            Brand Awareness Q1            71
8        Product Launch - Video            84
9           Competitor Conquest           288
10    Summer Sale - Retargeting           130
11    Summer Sale - Retargeting             4
12         App Install Campaign            11
13         Dynamic Search Ads               1
14              Holiday Promo               1
15         Brand Awareness Q1               1
16       New User Acquisition              49
17         New User Acquisition            16
18     Product Launch - Video               3
19             Back to School              12
20                Holiday Promo             6
21           Dynamic Search Ads           311
22           Brand Awareness Q1             3
23              YouTube Bumpers           203
24            YouTube Bumpers              21
25        Competitor Conquest              39
26              YouTube Bumpers             8
27       App Install Campaign              33
28           Dynamic Search Ads            20
29       Product Launch - Video             6
30  Summer Sale - Retargeting              18
31          Competitor Conquest            16
32               Back to School            76
33        Competitor Conquest               2
34       App Install Campaign               2
35              Holiday Promo               4

In [8]:
conn.execute("select distinct channel from raw.google_ads").fetchdf()

             channel
0        Paid Search
1   product_shopping
2             search
3              video
4            Display
5           SHOPPING
6             Search
7      youtube_video
8    display_network
9           shopping
10            SEARCH
11       paid_search
12             Video
13             VIDEO
14           display
15           DISPLAY
16          Shopping

In [9]:
duckdb.read_json("../raw_data/segment/segment_tracks.jsonl")

┌──────────────────────────────────┬─────────┬────────────────┬─────────────────────────┬─────────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────┐
│            message_id            │  type   │     event      │        timestamp        │ user_id │ anonymous_id │                                                                                                                                   properties                                                                                                                                   │                                       context                                       │
│             varchar              │ varchar │    varchar     │         varchar         │ varchar │   varchar    │                  struct(campaign_id varchar, channel varchar, page_url varchar, product_id varchar, time_on_page bigint, product_name varchar, price_usd double, quantity bigint, query varchar, results_count bigint, cart_total double, item_count bigint)                   │      struct(library_name varchar, library_version varchar, user_agent varchar)      │
├──────────────────────────────────┼─────────┼────────────────┼─────────────────────────┼─────────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────┤
│ e12db95e35b3a3ba7781549134c83a37 │ track   │ product_view   │ 2025-04-04 11:03:56 UTC │ u_04441 │ anon_292484  │ {'campaign_id': 8, 'channel': display, 'page_url': 'https://example.com/products', 'product_id': prod_7674, 'time_on_page': 85, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}       │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 1731612ea6e6517473c2112e691712dc │ track   │ add_to_cart    │ 2025-04-04 06:19:29 UTC │ u_00275 │ anon_378001  │ {'campaign_id': 6, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': prod_4406, 'time_on_page': NULL, 'product_name': Widget Pro, 'price_usd': 15.42, 'quantity': 2, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}   │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ d50e163802c1805773b5bf0d5f08fe78 │ track   │ search         │ 2025-04-04 17:53:01 UTC │ u_04133 │ anon_929916  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/about', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': best price, 'results_count': 36, 'cart_total': NULL, 'item_count': NULL}         │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 5356363679948e55b63121271e6ff87e │ track   │ page_view      │ 2025-04-04 04:56:51 UTC │ u_04773 │ anon_778044  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}           │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ bc6577be86e654029e94798d7554b32c │ track   │ search         │ 2025-04-04 08:12:02 UTC │ u_00528 │ anon_982347  │ {'campaign_id': 11, 'channel': search, 'page_url': 'https://example.com/about', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': widget, 'results_count': 9, 'cart_total': NULL, 'item_count': NULL}              │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 34cd6d60c36e25e480010c3f46c73a72 │ track   │ add_to_cart    │ 2025-04-04 05:52:35 UTC │ u_00385 │ anon_393948  │ {'campaign_id': 12, 'channel': display, 'page_url': 'https://example.com/pricing', 'product_id': prod_7403, 'time_on_page': NULL, 'product_name': Thing Plus, 'price_usd': 62.53, 'quantity': 3, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL} │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ c54ba8a0060e356580b41ccbc67c6b55 │ track   │ add_to_cart    │ 2025-04-04 04:33:09 UTC │ u_01630 │ anon_345128  │ {'campaign_id': 6, 'channel': search, 'page_url': 'https://example.com/home', 'product_id': prod_3233, 'time_on_page': NULL, 'product_name': Widget Pro, 'price_usd': 48.98, 'quantity': 4, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}      │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ a6bb7f803a6e3afa899a53d80a81a962 │ track   │ add_to_cart    │ 2025-04-04 00:14:01 UTC │ u_01766 │ anon_365959  │ {'campaign_id': 5, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': prod_8675, 'time_on_page': NULL, 'product_name': Doohickey, 'price_usd': 29.63, 'quantity': 1, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}    │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 015cb0ae6eee71d08adb2624314570cf │ track   │ checkout_start │ 2025-04-04 00:28:54 UTC │ u_03738 │ anon_913596  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': 495.54, 'item_count': 6}            │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ ba95d0f99459d0e6f6c6f8026f7d992c │ track   │ page_view      │ 2025-04-04 05:17:41 UTC │ u_02041 │ anon_158772  │ {'campaign_id': 12, 'channel': display, 'page_url': 'https://example.com/home', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}             │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│                ·                 │   ·     │   ·            │            ·            │    ·    │      ·       │                                                                                                                                 ·                                                                                                                                              │                                          ·                                          │
│                ·                 │   ·     │   ·            │            ·            │    ·    │      ·       │                                                                                                                                 ·                                                                                                                                              │                                          ·                                          │
│                ·                 │   ·     │   ·            │            ·            │    ·    │      ·       │                                                                                                                                 ·                                                                                                                                              │                                          ·                                          │
│ 7842242cc1486c9fdc388ee99f8d4cda │ track   │ search         │ 2025-04-18 21:15:08 UTC │ u_03495 │ anon_943901  │ {'campaign_id': 5, 'channel': search, 'page_url': 'https://example.com/about', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': best price, 'results_count': 33, 'cart_total': NULL, 'item_count': NULL}          │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 81232153e5b09f03979b117c146b03de │ track   │ checkout_start │ 2025-04-18 19:24:26 UTC │ u_04990 │ anon_982322  │ {'campaign_id': 1, 'channel': search, 'page_url': 'https://example.com/home', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': 458.27, 'item_count': 7}                │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 35ef2ce7fd211ae2350d015262c2e35b │ track   │ checkout_start │ 2025-04-18 08:44:58 UTC │ N/A     │ anon_191073  │ {'campaign_id': 6, 'channel': search, 'page_url': 'https://example.com/home', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': 683.6, 'item_count': 7}                 │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 570e7fffd8588c61c940a2f216fc21db │ track   │ page_view      │ 2025-04-18 12:38:33 UTC │ u_01044 │ anon_491697  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/home', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}              │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 80c76c6657ffc93a5ddd23e4c3ed457d │ track   │ product_view   │ 2025-04-18 09:28:54 UTC │ u_03567 │ anon_905657  │ {'campaign_id': 11, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': prod_1497, 'time_on_page': 186, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}       │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ b29c61d93994645c7d9cd64018aba6c4 │ track   │ search         │ 2025-04-18 06:06:14 UTC │ u_00840 │ anon_992705  │ {'campaign_id': 21, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': widget, 'results_count': 47, 'cart_total': NULL, 'item_count': NULL}           │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 04d6235ef06cdf801aa37dd9d4d8bf97 │ track   │ product_view   │ 2025-04-18 00:52:04 UTC │ u_00927 │ anon_113476  │ {'campaign_id': 5, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': prod_6034, 'time_on_page': 52, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': NULL, 'results_count': NULL, 'cart_total': NULL, 'item_count': NULL}         │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 4352d98ae10769d50aada755cfde1c8c │ track   │ search         │ 2025-04-18 06:45:34 UTC │ u_04397 │ anon_166316  │ {'campaign_id': 21, 'channel': search, 'page_url': 'https://example.com/products', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': widget, 'results_count': 4, 'cart_total': NULL, 'item_count': NULL}           │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ d28885e244ec4b6f48edececeab066c2 │ track   │ search         │ 2025-04-18 14:39:00 UTC │ u_04673 │ anon_910085  │ {'campaign_id': 8, 'channel': display, 'page_url': 'https://example.com/products', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': review, 'results_count': 42, 'cart_total': NULL, 'item_count': NULL}          │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
│ 0faa17373030ce5f48de0d1cf2754e24 │ track   │ search         │ 2025-04-18 18:45:02 UTC │ u_01908 │ anon_718869  │ {'campaign_id': 15, 'channel': search, 'page_url': 'https://example.com/pricing', 'product_id': NULL, 'time_on_page': NULL, 'product_name': NULL, 'price_usd': NULL, 'quantity': NULL, 'query': discount, 'results_count': 45, 'cart_total': NULL, 'item_count': NULL}         │ {'library_name': analytics.js, 'library_version': 2.9.0, 'user_agent': Mozilla/5.0} │
└──────────────────────────────────┴─────────┴────────────────┴─────────────────────────┴─────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                                                               8 columns

In [10]:
conn.execute("""
    CREATE TABLE IF NOT EXISTS raw.segment_tracks AS
    SELECT 
        message_id,
        type,
        event,
        timestamp,
        user_id,
        anonymous_id,
        json(properties) as properties,
        json(context) as context,
        session_id
             
    FROM read_json('../raw_data/segment/segment_tracks.jsonl', sample_size=-1)

""")

**sample_size=-1 to force DuckDB to scan the entire file before inferring the schema**



[DuckDB Loading JSON Documentation](https://duckdb.org/docs/current/data/json/loading_json)

In [11]:
conn.execute("describe raw.segment_tracks").fetchdf()

    column_name column_type null   key default extra
0    message_id        UUID  YES  None    None  None
1          type     VARCHAR  YES  None    None  None
2         event     VARCHAR  YES  None    None  None
3     timestamp     VARCHAR  YES  None    None  None
4       user_id     VARCHAR  YES  None    None  None
5  anonymous_id     VARCHAR  YES  None    None  None
6    properties        JSON  YES  None    None  None
7       context        JSON  YES  None    None  None
8    session_id     VARCHAR  YES  None    None  None

In [12]:
conn.execute("select * from raw.segment_tracks where message_id = 'e12db95e35b3a3ba7781549134c83a37' ").fetch_df()

,message_id,type,event,timestamp,user_id,anonymous_id,properties,context,session_id
0,e12db95e-35b3-a3ba-7781-549134c83a37,track,product_view,2025-04-04 11:03:56 UTC,u_04441,anon_292484,"{""campaign_id"":""8"",""channel"":""display"",""page_u...","{""library_name"":""analytics.js"",""library_versio...",None

In [13]:

conn.execute("select * from raw.segment_tracks where message_id = 'fde6a9fa2641d21500f4862e5f687ec4' ").fetch_df()

,message_id,type,event,timestamp,user_id,anonymous_id,properties,context,session_id
0,fde6a9fa-2641-d215-00f4-862e5f687ec4,track,page_view,2025-07-03 14:22:06 UTC,u_04671,anon_698079,"{""campaign_id"":""5"",""channel"":""search"",""page_ur...","{""library_name"":""analytics.js"",""library_versio...",sess_84599834

In [14]:
conn.execute("INSTALL postgres; LOAD postgres;")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [15]:
conn.execute("""
    CREATE TABLE IF NOT EXISTS raw.app_conversions AS 
    SELECT * FROM postgres_scan(
        'host=localhost port=5432 dbname=marketing_attribution user=analytics password=analytics',
        'public',
        'app_conversions'
    )
""")

In [16]:
conn.execute("show all tables").fetch_df()

,database,schema,name,column_names,column_types,temporary
0,marketing_data,raw,app_conversions,"[conversion_id, usr_id, cmpgn_id, conv_type_cd...","[INTEGER, INTEGER, INTEGER, INTEGER, DECIMAL(1...",False
1,marketing_data,raw,google_ads,"[date, campaign_id, campaign_name, channel, sp...","[VARCHAR, BIGINT, VARCHAR, VARCHAR, DOUBLE, BI...",False
2,marketing_data,raw,segment_tracks,"[message_id, type, event, timestamp, user_id, ...","[UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VAR...",False

In [17]:
conn.execute("select * from raw.app_conversions limit 10").fetch_df()

,conversion_id,usr_id,cmpgn_id,conv_type_cd,revenue_amt,conv_ts,created_at
0,1,4197,1,1,365.30,2025-04-04 18:00:32+00:00,2025-04-04T18:00:32Z
1,2,2512,20,2,NaN,2025-04-04 17:51:03+00:00,2025-04-04T17:51:03Z
2,3,1178,21,3,NaN,2025-04-04 15:26:21+00:00,2025-04-04T15:26:21Z
3,4,3425,1,3,NaN,2025-04-04 16:27:09+00:00,2025-04-04T16:27:09Z
4,5,1733,21,3,NaN,2025-04-04 09:14:53+00:00,2025-04-04T09:14:53Z
5,6,2077,11,1,269.98,2025-04-04 16:18:23+00:00,2025-04-04T16:18:23Z
6,7,4859,1,4,3635.38,2025-04-04 02:40:27+00:00,2025-04-04T02:40:27Z
7,8,2702,21,4,4936.31,2025-04-04 07:16:45+00:00,2025-04-04T07:16:45Z
8,9,1355,15,2,NaN,2025-04-04 15:01:13+00:00,2025-04-04T15:01:13Z
9,10,4980,11,1,10.77,2025-04-04 09:56:43+00:00,2025-04-04T09:56:43Z

In [18]:
conn.sql("call start_ui()")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌──────────────────────────────────────┐
│                result                │
│               varchar                │
├──────────────────────────────────────┤
│ UI started at http://localhost:4213/ │
└──────────────────────────────────────┘

In [19]:
duckdb.__version__

'1.5.1'